replicaCount: 3

image:
  repository: vikasgirigoswami/last
  tag: latest
  pullPolicy: IfNotPresent

# service:
#   port: 3000

# config:
#   DB_HOST: localhost
#   DB_PORT: "5432"

# secret:
#   POSTGRES_USER: myuser
#   POSTGRES_PASSWORD: mypassword
#   POSTGRES_DB: mydb

namespace: 2-assignment
